import { promises as fs } from 'fs';
import * as path from 'path';

export async function generateHtmlPage(
  title: string,
  content: string, // This will be the HTML converted from Markdown
  outPath: string,
  options: {
    siteName?: string;
    backLink?: string;
  } = {}
) {
  const siteName = options.siteName || 'feedme';
  const backLinkHtml = options.backLink ? `<a href="${options.backLink}" class="link blue hover-dark-blue mb3 dib">&larr; Back to ${siteName}</a>` : '';

  const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${title} - ${siteName}</title>
  <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
  <style>
    /* Small custom overrides for reading comfort */
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
    .content img { max-width: 100%; height: auto; }
    .content pre { overflow-x: auto; padding: 1rem; background: #f4f4f4; border-radius: 4px; }
    .content blockquote { border-left: 4px solid #ccc; padding-left: 1rem; margin-left: 0; color: #555; }
  </style>
</head>
<body class="w-100 sans-serif bg-white black-80 pa3 pa4-m pa5-l">
  <main class="center measure-wide lh-copy">
    ${backLinkHtml}
    
    <article class="content">
      <h1 class="f2 f1-m f-headline-l lh-title mt0 mb3">${title}</h1>
      ${content}
    </article>
    
    <footer class="mt5 pt4 bt b--black-10 f6 gray">
      <p>Automatically generated by <a href="https://feedme.app" class="link blue">feedme</a>.</p>
    </footer>
  </main>
</body>
</html>`;

  await fs.writeFile(outPath, htmlTemplate);
}

export async function generateIndexPage(
  items: { title: string; link: string; date: string; slug: string }[],
  outPath: string,
  siteName: string = 'My Feed Archive'
) {
  const itemsHtml = items.map(item => `
    <li class="pv3 ba bl-0 bt-0 br-0 b--black-10">
      <a href="./${item.slug}.html" class="link blue hover-dark-blue f4 fw6 db mb2">${item.title}</a>
      <div class="f6 gray">
        <time>${new Date(item.date).toLocaleDateString()}</time> &bull; 
        <a href="${item.link}" target="_blank" rel="noopener" class="link gray hover-blue">Original Source</a>
      </div>
    </li>
  `).join('\n');

  const htmlTemplate = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${siteName}</title>
  <link rel="stylesheet" href="https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css"/>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
  </style>
</head>
<body class="w-100 sans-serif bg-white black-80 pa3 pa4-m pa5-l">
  <main class="center measure-wide lh-copy">
    <header class="mb5">
      <h1 class="f2 f1-m lh-title mt0 mb2">${siteName}</h1>
      <p class="f4 gray mt0">An automated RSS archive.</p>
    </header>
    
    <ul class="list pl0 mt0 measure center">
      ${itemsHtml}
    </ul>
    
    <footer class="mt5 pt4 bt b--black-10 f6 gray">
      <p>Powered by <a href="https://feedme.app" class="link blue">feedme</a>.</p>
    </footer>
  </main>
</body>
</html>`;

  await fs.writeFile(outPath, htmlTemplate);
}
